### ISSUE TITLE
Different appearance for cursor in passive panel

### ISSUE THREAD

**Issue by marcushenningsen** [MeanEYE/Sunflower#192]
It is hard to determine which panel is active because both have a cursor with the same appearance.

The issue is already described in two old cases:

https://code.google.com/archive/p/sunflower-fm/issues/234
https://code.google.com/archive/p/sunflower-fm/issues/189

However, the problem still persists, and I can't seem to find a solution.

Here is the screenshot:

![screenshot from 2016-02-10 16 31 13](https://cloud.githubusercontent.com/assets/11071238/12951704/e0bafb5c-d013-11e5-8103-78e6dca0b82b.png)

Sunflower version is 0.3 (61).

From the old issues it seems the problem is dependant on the theme. Could you then explain how that it so and perhaps for which theme item I should look for if I wanted to tweak the color of the inactive cursor?

Kind regards,
Marcus Henningsen

**Comment by MeanEYE** [comment]
Hi and thanks for reporting this issues. My original idea was to use tab title bar to indicate which list is selected. As you can see on your screen shot left list is selected as it has dark title bar showing `../Pictures`.

Sadly for GTK2 this is the only way I can highlight active list other than rendering the whole list on my own, which as you might expect is quite a bit of work and brings a whole new set of problems.

However, this issue was already solved for version 0.4 as you can 
![see in my screen shot](https://cloud.githubusercontent.com/assets/1911594/12955063/9dc2f54e-d021-11e5-81f8-b236bf5d34a2.png).

**Comment by marcushenningsen** [comment]
Thanks for the quick response, especially since it's a minor issue.

The tab title bar highlighting works well, however, I (and probably the others who reported the same issue) still get confused in my daily work, likely because I'm used to work with Total Commander or similar programs that have the cursor color differ.

Where  can I find version 0.4? I only see the 0.3 (61).

**Comment by MeanEYE** [comment]
I understand your issue and wish there was something more I could do to help. Sadly that would require, like I said, a lot more work and product a lot more issues in the process and reduce responsiveness of the program.

Version 0.4 is not released yet. That version is first version to use GTK3, as opposed to GTK2 until now. GTK3 allows us to do some really nice things with widgets and allows us to slightly modify themes like you see on screen shot I've provided.

There are GTK2 themes which do provide the same functionality, but I don't know any by heart right now. Sorry about that.

**Comment by marcushenningsen** [comment]
Alright, no problem, and thanks for taking the time to answer. I'll keep my
eyes open for the 0.4 release.

Good work with the fm by the way =)

**Comment by MeanEYE** [comment]
Thanks. Am going to close this issue now as it's been fixed already for next release. I'll give my best for this release to come soon.
