### ISSUE TITLE
Can't install new version 0.4 (62) on Debian 10

### ISSUE THREAD

**Issue by lfromanini** [MeanEYE/Sunflower#409]
The new release 0.4 (62) is incompatible with Debian Buster (stable), since one dependency could not be satisfied (gir1.2-glib-2.0 (>= 1.60)), as below:

```bash
sudo dpkg -i sunflower-0.4.62-1.all.deb
Selecting previously unselected package sunflower.
(Reading database ... 485368 files and directories currently installed.)
Preparing to unpack sunflower-0.4.62-1.all.deb ...
Unpacking sunflower (0.4.62) ...
dpkg: dependency problems prevent configuration of sunflower:
 sunflower depends on gir1.2-glib-2.0 (>= 1.60); however:
  Version of gir1.2-glib-2.0:amd64 on system is 1.58.3-2.

dpkg: error processing package sunflower (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 sunflower
```

My system is already updated with the latest software available for stable branch.

**Comment by MeanEYE** [comment]
Can you please clone the directory and try running with `python3 -m sunflower`? There's absolutely no reason why we would require 1.60 and not work with 1.58 of that same library.

**Comment by lfromanini** [comment]
Of course! Doing as you mentioned, Sunflower worked. Perhaps the issue is related with .deb file.

**Comment by MeanEYE** [comment]
Issue is with package file. Sorry about that. I tested versions with my own system which is on Debian Testing, and those versions are newer than needed. There are some other dependencies that are wrong as well. Am checking them all as we speak and I think we should reasonably be able to support `oldstable` (Stretch) without too many issues.

Give me few more moments and I'll build new packages for you. Sorry for the inconvenience.

**Comment by MeanEYE** [comment]
Fixed. Please download again and try!

**Comment by lfromanini** [comment]
Downloading from https://sunflower-fm.org/download, it is the same version as before (sunflower-0.4.62-1.all.deb) and leads to the same behavior. Should I try another URL? Which one?

**Comment by MeanEYE** [comment]
I didn't change the version number at all. This is just packaging issue, although I should have probably changed the package number. Let me double-check that version online is the correct one.

**Comment by MeanEYE** [comment]
Yeah, I just downloaded version from the link you provided and dependency is fine now. Please make sure you are not installing the old one. I know it's confusing with the same file name. I'll have to fix our build system.

**Comment by lfromanini** [comment]
For sure, it is the new download and the problem is still there. I replaced the old one and now it is gone forever. :)

But I did a check sum, for convenience:

```bash
md5sum sunflower-0.4.62-1.all.deb
26fc5d297c15dfe1e2a294124c3e7ef9  sunflower-0.4.62-1.all.deb
```

**Comment by MeanEYE** [comment]
For some reason you are getting the old version. Perhaps some cache issue, my MD5 is `19cefec31ef4f4857b89fe7732016d93`. Anyway... I'll attach the file here.
[sunflower-0.4.62-1.all.deb.zip](https://github.com/MeanEYE/Sunflower/files/4653296/sunflower-0.4.62-1.all.deb.zip)

Just rename it, since GitHub doesn't allow `.deb` files here.

**Comment by lfromanini** [comment]
Now it is working fine! Thank you very much! I'll close the issue.

**Comment by MeanEYE** [comment]
You are welcome. Glad we could solve this one easily. Enjoy! Let me know if you have any other issues.
